[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Environment variables - Add these in Netlify UI
# Site settings → Environment variables → Add a variable
# Required:
# - OAUTH_CLIENT_ID (from GitHub OAuth App)
# - OAUTH_CLIENT_SECRET (from GitHub OAuth App)
