backend:
  name: github
  repo: lukegvoigt/vnr-website
  branch: main
  base_url: https://valdostanorthrotary.netlify.app
  auth_endpoint: /.netlify/functions/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "pages"
    label: "Pages"
    files:
      - name: "upcoming"
        label: "Upcoming Page"
        file: "src/data/upcoming.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Upcoming Events & Announcements" }
          - { label: "Page Content", name: "body", widget: "markdown", hint: "Edit the content of the Upcoming page here. Use markdown formatting." }
